import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { getReviewForSlug } from '../../actions/review';
import OrderReview from './OrderReview';

// review dynamically generated by users who have ordered products
const OrderReviews = ({
  review: { reviews, loading },
  getReviewForSlug,
  slug,
}) => {
  useEffect(() => {
    getReviewForSlug(slug);
  }, [getReviewForSlug]);

  if (loading) return <div> I am loading! </div>;

  return (
    <>
      <h1>This is the dynamic order reviews</h1>

      {reviews &&
        reviews.length > 0 &&
        reviews.map(review => <OrderReview key={review._id} review={review} />)}
    </>
  );
};

const mapStateToProps = state => ({
  review: state.review,
});

export default connect(
  mapStateToProps,
  { getReviewForSlug },
)(OrderReviews);
