import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { getReviewForSlug } from '../../actions/review';

// review dynamically generated by users who have ordered products
const OrderReviews = ({ review, getReviewForSlug, slug }) => {
  useEffect(() => {
    getReviewForSlug(slug);
  }, [getReviewForSlug]);
  return (
    <>
      <h1>This is the dynamic order reviews</h1>
      This is the order reviews
      <pre>{JSON.stringify(review, null, 2)}</pre>
    </>
  );
};

const mapStateToProps = state => ({
  review: state.review,
});

export default connect(
  mapStateToProps,
  { getReviewForSlug },
)(OrderReviews);
